### ISSUE TITLE
[Azure] Empty `trusted_certificates` param causes `config-director.sh` to fail

### ISSUE THREAD

**Issue by wrast** [pivotal-cf/pcf-pipelines#181]
The `install-pcf/azure/tasks/iaas/config-director.sh` script fails with the error below when the `trusted_certificates` param in `params.yml` doesn't have a value. Here's the relevant code from `config-director.sh`:

```
# Fill in trusted certificates
SECURITY_TOKENS=$(jq -n \
  --arg trusted_cert "${TRUSTED_CERTIFICATES}" \
  '{
    "trusted_certificates": $trusted_cert,
    "generate_vm_passwords": true
  }')

om-linux \
  --target https://$OPSMAN_DOMAIN_OR_IP_ADDRESS \
  --skip-ssl-validation \
  --username $PCF_OPSMAN_ADMIN \
  --password $PCF_OPSMAN_ADMIN_PASSWORD \
  configure-bosh \
  --security-configuration "${SECURITY_TOKENS}"
```

We also tried to hardcode a `null` value in place of `$trusted_cert` in `config-director.sh` which didn't work either. When we supplied an actual `trusted_certificates` value in `params.yml` the task/job was successful.

Error encountered in Concourse job `config-director`:
```
####################################################################
PUSHING CONFIG FOR: DIRECTOR -> resources <- file ...
####################################################################
 <html><body>You are being <a href="https://opsman.azure.merrill.ecsteam.io/infrastructure/director/resources/edit">redirected</a>.</body></html> # [ 0]BsZWdrY2NxNnR2cG44YUczdDI5bitJNHZwOUJjalowVzV3RC9hUzkwa242eHE1RlFaSW1icUtzTFp0ZTB2WkxBK0hINjFjTklrc0Jlbm5yanpzRVIyRUpXRW5QZ3cvdjZzbDZmMDlWK0xDZ3c4WDhpN0RFMVRTV0w3TDlaQk5XbkNLRG53UTQ4Y3VYVlhTbDROU1MzVFhvMmVPQWkvRUdpSy0tSlUvTSt4enRQUVRWZVJRY1pXQzcwdz09--f3f5cb8c1470e8bb4978d762e880b007056dfde9; path=/; secure; HttpOnlyct_resources_form%5Bdirector%5D%5Belb_names%5D=&product_resources_form%5Bdirector%5D%5Binternet_connected%5D=0&product_resources_form%5Bdirector%5D%5Bvm_type_id%5D=" DEBUG_CMD=curl -k -s -i --cookie mycookiejar --cookie-jar mycookiejar -X POST -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.8" -H "Cache-Control: max-age=0" -H "Connection: keep-alive" -H "Host: opsman.azure.merrill.ecsteam.io" -H "Upgrade-Insecure-Requests: 1" -H "Content-Type: application/x-www-form-urlencoded" -d "utf8=%E2%9C%93&_method=put&authenticity_token=jwJ7eeAEElPHDXNWOtJYNZvzCcQ9DAOD3NR6ZKIl9xbKtETzpqrB4dgItRnmv9GNBG6e8d8hn9TQaoCqFtJlZw%3D%3D&product_resources_form%5Bcompilation%5D%5Bdisk_type_id%5D=&product_resources_form%5Bcompilation%5D%5Belb_names%5D=&product_resources_form%5Bcompilation%5D%5Binternet_connected%5D=0&product_resources_form%5Bcompilation%5D%5Bvm_type_id%5D=&product_resources_form%5Bdirector%5D%5Bdisk_type_id%5D=&product_resources_form%5Bdirector%5D%5Belb_names%5D=&product_resources_form%5Bdirector%5D%5Binternet_connected%5D=0&product_resources_form%5Bdirector%5D%5Bvm_type_id%5D=" 'https://opsman.azure.merrill.ecsteam.io/infrastructure/director/resources' DEBUG_CMD_LEN=1106 curl -k -s -i --cookie mycookiejar --cookie-jar mycookiejar -X POST -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.8" -H "Cache-Control: max-age=0" -H "Connection: keep-alive" -H "Host: opsman.azure.merrill.ecsteam.io" -H "Upgrade-Insecure-Requests: 1" -H "Content-Type: application/x-www-form-urlencoded" -d "utf8=%E2%9C%93&_method=put&authenticity_token=jwJ7eeAEElPHDXNWOtJYNZvzCcQ9DAOD3NR6ZKIl9xbKtETzpqrB4dgItRnmv9GNBG6e8d8hn9TQaoCqFtJlZw%3D%3D&product_resources_form%5Bcompilation%5D%5Bdisk_type_id%5D=&product_resources_form%5Bcompilation%5D%5Belb_names%5D=&product_resources_form%5Bcompilation%5D%5Binternet_connected%5D=0&product_resources_form%5Bcompilation%5D%5Bvm_type_id%5D=&product_resources_form%5Bdirector%5D%5Bdisk_type_id%5D=&product_resources_form%5Bdirector%5D%5Belb_names%5D=&product_resources_form%5Bdirector%5D%5Binternet_connected%5D=0&product_resources_form%5Bdirector%5D%5Bvm_type_id%5D=" 'https://opsman.azure.merrill.ecsteam.io/infrastructure/director/resources' HTTP/1.1 302 Moved Temporarily
configuring security options for bosh tile
could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Thu, 07 Sep 2017 18:22:32 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: _web_session=bFErdFVVeG0zdWtqdU9qMlhzM25XUE1PZkluRWliYmMzWDdkdmpQWUFtd1dndUZTYnlGNmhEeklhSXZSUHlnRGhjTVV3OHVGUUIxdnBzeUFxSHN2K25WM3QrWTBsL3BCV3Mvc01WNmx5Rk5nNWpTZzZFVGFJNFBmT2p5cDcyYTZpSHB6REExclNFNmZVRmRabzdtMGhBPT0tLWJNSHkramI2akpMTFE4WWlNS3N6Qnc9PQ%3D%3D--67433353ad2309b847627ace70f03c368f8db135; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 824d23fd-3f4c-42b5-9f58-e5014b69e8bf
X-Runtime: 0.094242
X-Xss-Protection: 1; mode=block

2a6f
<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
<meta content='0' http-equiv='expires'>
<meta content='text/javascript' http-equiv='Content-Script-Type'>
<meta content='text/css' http-equiv='Content-Style-Type'>
<meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
<link href='/favicon.png' rel='icon' type='image/png'>
<title>Ops Manager</title>
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="rcaFGQKlS25L6Ck7T9qmPDTA5rETVK9r+xVV1pGajOwK7HNF1eYNQYH2bMgiCD2Wja6v9ObufuCGBVhQNCcoZw==" />
<link rel="stylesheet" media="screen" href="/assets/application-2c29ca884d37864467d5334e1c4883aa2e3c58c564e77a00d4c3b12fe66bb4b0.css" />
<script src="/assets/application-3f515a698587bf8a738bf1f5f944a2c08fed10676595d017d6de9b2eb2cbd9fb.js"></script>


</head>
<body class='error-page rails-env-production'>
<div class='container'>
<nav class='site-header'>
<a class='logo float-left' href='/' id='pivotal_cf_logo'>
<div class='pivotal-logo'></div>
<div class='operations-manager-logo'></div>
</a>
</nav>
<section class='content-container twelve columns'>
<div class='error'>
<h1>500 An error occurred.</h1>
<h2>Contact Pivotal Technical Support to report the problem.</h2>

<p><a href="/">Back to dashboard</a></p>
<hr>
<pre>NoMethodError</pre>
<pre>undefined method `[]' for nil:NilClass</pre>
<pre>/home/tempest-web/tempest/web/app/controllers/infrastructure/security_tokens_controller.rb:7:in `update'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
/home/tempest-web/tempest/web/lib/rack/streaming.rb:63:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `call'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'</pre>
<hr>
<p class='footer'><a href="/">Back to dashboard</a></p>
</div>
</section>
<footer class='site-footer'>
<span class='version'>PCF Ops Manager v1.10.15.0;</span>
<span>&copy;2013-2017 Pivotal Software, Inc; All Rights Reserved.</span>
<span class='float-right'><a href="/eula">End User License Agreement</a></span>
<span class='float-right'>&nbsp;|&nbsp;</span>
<span class='float-right'><a href="/docs">API Docs</a></span>
</footer>

</div>
</body>
</html>
```

**Comment by abbyachau** [comment]
Hi @wrast thanks for raising this issue. We've prioritised this in the backlog - however, please let us know if this is a showstopper. Thanks.

**Comment by wrast** [comment]
Not a showstopper. It just requires a value to get past the error.

**Comment by abbyachau** [comment]
hey @wrast thanks again for reporting this issue. Closing this issue because we've implemented a fix for this. Please let us know if you have any questions. Thanks.
