### ISSUE TITLE
[openstack] configure-director fails when using `pre_os_cacert:`

### ISSUE THREAD

**Issue by rkoster** [pivotal-cf/pcf-pipelines#255]
I get the following error:
```
From cffi callback <function _verify_callback at 0x7f25fb319d70>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Failed to discover available identity versions when contacting https://horizon.company.com:5000/v3. Attempting to parse version from URL.
From cffi callback <function _verify_callback at 0x7f25fb0bc140>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
SSL exception connecting to https://horizon.company.com:5000/v3/auth/tokens: HTTPSConnectionPool(host='horizon.company.com', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))
```

**Comment by rkoster** [comment]
the issue happend when using config-director on openstack with API_SSL_CERT https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/openstack/tasks/config-director/task.sh#L5-L8
