### ISSUE TITLE
GCP: Configure BOSH Director is repeatedly failing

### ISSUE THREAD

**Issue by goutamtadi1** [pivotal-cf/pcf-pipelines#321]
## Issue
with V0.23.1, Opsman is successfully installed, Configuring BOSH director failed

### Expected result

Complete Configuring BOSH director successfully

### Current result
```
	
Configuring IaaS and Director...
	
configuring iaas specific options for bosh tile
	
configuring director options for bosh tile
	
configuring security options for bosh tile
	
configuring resources for bosh tile
	
configuring availability zones for bosh tile
	
configuring network options for bosh tile
	
could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
	
HTTP/1.1 500 Internal Server Error
	
Transfer-Encoding: chunked
	
Cache-Control: no-cache, no-store
	
Connection: keep-alive
	
Content-Type: text/html; charset=utf-8
	
Date: Fri, 13 Apr 2018 22:27:55 GMT
	
Expires: Fri, 01 Jan 1990 00:00:00 GMT
	
Pragma: no-cache
	
Server: nginx/1.4.6 (Ubuntu)
	
Set-Cookie: _web_session=NjNnWE1zeHZHYm1rTmF4K05WcytwK2c1THh0alhSSmNITExlOFdaWWJqeEs0aWIwOXpYMFVwalZQbGUrNnc2aTllTUdXK2FZR25zVFEvZnpmUG42S0hMekRBbnNOTWVRaFVDRS9reTJzR2JxS2ZMcnRTYVFnUmo5OURVNzJZcWl5L0NrcEdWcWVEYUU0dVZmZTRhclNnPT0tLTdITmswUWRrRHQ1UVFQRGgxZkE4SWc9PQ%3D%3D--65aec988b1d83f2d461d0a86ffa259026982c70a; path=/; secure; HttpOnly
	
Strict-Transport-Security: max-age=15552000
	
X-Content-Type-Options: nosniff
	
X-Frame-Options: SAMEORIGIN
	
X-Request-Id: 353afac4-2e70-4112-a2c1-be87a3c26896
	
X-Runtime: 0.203689
	
X-Xss-Protection: 1; mode=block
	

	
2bb9
	
<!DOCTYPE html>
	
<html>
	
<head>
	
<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
	
<meta content='0' http-equiv='expires'>
	
<meta content='text/javascript' http-equiv='Content-Script-Type'>
	
<meta content='text/css' http-equiv='Content-Style-Type'>
	
<meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
	
<link href='/favicon.png' rel='icon' type='image/png'>
	
<title>Ops Manager</title>
	
<meta name="csrf-param" content="authenticity_token" />
	
<meta name="csrf-token" content="cbRrbvonjuKc6k8JeAU/xXSiP+YFEWu2yFE4O6J2NQD+WEGAVuqpyUPFHMO/SZVpvaD7OHZGzJDGmUqo8yCZkA==" />
	
<link rel="stylesheet" media="screen" href="/assets/application-bd2cd61e06e7e298f373f3612c3c1ba12023ad1786c2a5ff89ce73622304fa86.css" />
	
<script src="/assets/application-6fccc2888a37f5cb7d80fbd0945e1c60b91c6d16d3ab7760b49454640e0e9510.js"></script>
	

	

	
</head>
	
<body class='error-page rails-env-production'>
	
<div class='container'>
	
<nav class='site-header'>
	
<a class='logo float-left' href='/' id='pivotal_cf_logo'>
	
<div class='pivotal-logo'></div>
	
<div class='operations-manager-logo'></div>
	
</a>
	
</nav>
	
<section class='content-container twelve columns'>
	
<div class='error'>
	
<h1>500 An error occurred.</h1>
	
<h2>Contact Pivotal Technical Support to report the problem.</h2>
	

	
<p><a href="/">Back to dashboard</a></p>
	
<hr>
	
<pre>NoMethodError</pre>
	
<pre>undefined method `service_network=' for #&lt;Persistence::Models::Network&gt;</pre>
	
<pre>/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
	
/home/tempest-web/tempest/web/app/models/persistence/framework/hashable_model.rb:75:in `block in initialize'
	
/home/tempest-web/tempest/web/app/models/persistence/framework/hashable_model.rb:74:in `each'
	
/home/tempest-web/tempest/web/app/models/persistence/framework/hashable_model.rb:74:in `initialize'
	
/home/tempest-web/tempest/web/app/presenters/networks_presenter.rb:57:in `new'
	
/home/tempest-web/tempest/web/app/presenters/networks_presenter.rb:57:in `block in load_networks_from_params'
	
/home/tempest-web/tempest/web/app/presenters/networks_presenter.rb:51:in `each'
	
/home/tempest-web/tempest/web/app/presenters/networks_presenter.rb:51:in `load_networks_from_params'
	
/home/tempest-web/tempest/web/app/presenters/networks_presenter.rb:18:in `initialize'
	
/home/tempest-web/tempest/web/app/controllers/infrastructure/networks_controller.rb:15:in `new'
	
/home/tempest-web/tempest/web/app/controllers/infrastructure/networks_controller.rb:15:in `update'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:188:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/conditional_get.rb:38:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/request_id.rb:24:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/static.rb:136:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/ssl.rb:84:in `call'
	
/home/tempest-web/tempest/web/lib/rack/streaming.rb:63:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
	
/home/tempest-web/tempest/web/lib/stack_prof_middleware.rb:78:in `call'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
	
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:1076:in `block in spawn_threadpool'</pre>
	
<hr>
	
<p class='footer'><a href="/">Back to dashboard</a></p>
	
</div>
	
</section>
	
<footer class='site-footer'>
	
<span class='version'>PCF Ops Manager v2.1-build.214;</span>
	
<span>&copy;2013-2018 Pivotal Software, Inc; All Rights Reserved.</span>
	
<span class='float-right'><a href="/eula">End User License Agreement</a></span>
	
<span class='float-right'>&nbsp;|&nbsp;</span>
	
<span class='float-right'><a href="/docs">API Docs</a></span>
	
</footer>
	

	
</div>
	
</body>
	
</html>
	

	
0
	
```

**Comment by Kenuat** [comment]
Have you found a fix for that issue?

**Comment by goutamtadi1** [comment]
No. I was not able to fix it. I configured it manually after creating opsman.
@Kenuat Where can I see this compatibility matrix to find right pipeline setup for PCF 2.1?
Thanks.
